name: Code Quality
# https://medium.com/swlh/enhancing-code-quality-with-github-actions-67561c6f7063

permissions:
  checks: write
  contents: write

on:
  push:
    branches:
      - "master"
    paths:
      - '**.py'
      - src/requirements.txt
  pull_request:
    paths:
      - '**.py'
      - src/requirements.txt

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          sudo apt-get install -y libmariadb-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Python linters
        run: pip install flake8 pylint

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          flake8: true
          flake8_args: |
            --ignore=E501
          continue_on_error: false
          pylint: true
          # https://github.com/pylint-dev/pylint/issues/8138
          pylint_args: |
            --disable=missing-class-docstring \
            --disable=missing-function-docstring \
            --disable=line-too-long \
            --disable=too-few-public-methods \
            --disable=W0511 \
            --disable=E1102 \
            --extension-pkg-whitelist=pydantic
